/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { useSession } from "next-auth/react";

export default function SajidResumeCenter() {
  const { status } = useSession();
  const [jd, setJd] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [apps, setApps] = useState<any[]>([]);
  const load = async () => { const r = await fetch("/api/jobs"); if (r.ok) setApps((await r.json()).applications || []); };
  useEffect(() => { if (status === "authenticated") { fetch("/api/sajid/bootstrap", { method: "POST" }).then(load); } }, [status]);
  const generate = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); setError(""); try { const r = await fetch("/api/jobs", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ jdText: jd, optimizeResume: true }) }); const d = await r.json(); if (!r.ok) throw new Error(d.error || "Generation failed"); setJd(""); await load(); } catch (x: any) { setError(x.message); } finally { setBusy(false); } };
  if (status === "loading") return <div className="text-neutral-400">Loading personal workspace...</div>;
  return <div className="max-w-6xl mx-auto space-y-8"><div><p className="text-xs uppercase tracking-widest text-emerald-400">Sajid Hossain / Personal Workspace</p><h1 className="text-3xl font-black text-white mt-2">JD to tailored resume</h1><p className="text-sm text-neutral-400 mt-2">Your base resume, role variants, GitHub projects, freelance history, and every generated PDF in one place.</p></div>{error && <div className="p-3 border border-red-800 bg-red-950/40 text-red-300 rounded-lg text-sm">{error}</div>}<form onSubmit={generate} className="space-y-4"><textarea value={jd} onChange={e => setJd(e.target.value)} required rows={10} placeholder="Paste the complete job description here..." className="w-full bg-neutral-950 border border-neutral-800 rounded-xl p-4 text-sm text-white focus:border-emerald-500 focus:outline-none" /><button disabled={busy || !jd.trim()} className="bg-emerald-400 text-black font-bold px-5 py-3 rounded-lg disabled:opacity-50">{busy ? "Analyzing, tailoring, and saving..." : "Generate tailored resume PDF"}</button></form><section><div className="flex items-center justify-between mb-3"><h2 className="text-lg font-bold text-white">Saved role versions</h2><Link href="/dashboard/jobs" className="text-xs text-emerald-400">Open application history</Link></div><div className="grid gap-3">{apps.map(a => <div key={a.id} className="border border-neutral-800 bg-neutral-900/60 rounded-xl p-4 flex items-center justify-between gap-4"><div><h3 className="font-bold text-white">{a.jobTitle || "Untitled role"}</h3><p className="text-xs text-neutral-400">{a.company || "Company unspecified"} · {a.matchScore ?? "-"}% match · {new Date(a.createdAt).toLocaleDateString()}</p></div><a target="_blank" rel="noreferrer" href={`/api/jobs/${a.id}/pdf/resume`} className="text-xs font-bold text-emerald-400 border border-emerald-500/30 px-3 py-2 rounded-lg">Download PDF</a></div>)}</div></section></div>;
}
